### ISSUE TITLE
Xamarin.Droid: A Microsoft Azure Mobile Services assembly for the current platform was not found

### ISSUE THREAD

**Issue by KeejOow** [msdxbelux/XamarinAlliance#4]
Dear,

When trying to complete Challenge 3, I added the Microsoft.Azure.Mobile.Client library to the shared project. However, during runtime I got the error referenced in the title. Initial searches yielded these suggestions: https://github.com/Azure/azure-mobile-apps-net-client/issues/271. So I added Microsoft.Azure.Mobile.Client to the Droid project without changing any additional code and then the error disappeared. Is this normal behaviour or is there any explanation as to why this happens?

If you need more details, please feel free to ask.

**Comment by KeejOow** [comment]
The specific error is the following

A Microsoft Azure Mobile Services assembly for the current platform was not found. Ensure that the current project references both Microsoft.WindowsAzure.Mobile and the following platform-specific assembly: Microsoft.WindowsAzure.Mobile.Ext.

**Comment by ntrogh** [comment]
@KeejOow You need to add the NuGet package also to the platform-specific projects. I'll update the challenge documentation to clarify this.
