### ISSUE TITLE
Use authentication in iOS

### ISSUE THREAD

**Issue by MasDevProject** [msdxbelux/XamarinAlliance#6]
Hi all,
I followed your guide for the 4° step.
I'm developing the application on iOS.
Unfortunately when I try to perform the LoginAsync method I get the following error:

(Google)
403
Error: disallowed_useragent

I didn't find a workaround on the web.
It seems that the Azure ddl uses a WebView but Google has deprecated it.

**Comment by ntrogh** [comment]
What version of the Microsoft.Azure.Mobile.Client NuGet package are you using? v3.1.0 should fix this for Windows and iOS. Android is still not fixed and will require the Google SDK to be used client-side.

**Comment by MasDevProject** [comment]
@ntrogh thank you for reply.
I'm using the v3.1.0.

This is my platform specific authenticate method:

`public async Task<bool> Authenticate()
		{
			var success = false;

			try
			{
				user = await CharacterService.Client.LoginAsync(UIApplication.SharedApplication.KeyWindow.RootViewController, MobileServiceAuthenticationProvider.Google);

				success = user != null;
			}
			catch (Exception ex)
			{
				// TODO handle UI
			}

			return success;
		}`

**Comment by ntrogh** [comment]
Checking with Mobile Apps SDK team.
In the meantime you could switch to an other provider (FB or Twitter) or use the Google SDK for auth and pass the access token to the MobileServiceClient.

**Comment by MasDevProject** [comment]
Using Facebook I get the following error:
`Facebook login this app is still in development mode...`

Using Twitter it works but using `https://xamarinalliancesecurebackend.azurewebsites.net` as service, I get a 500 Internal Server Error when I try to get the Characters list.

**Comment by ntrogh** [comment]
Issues with Twitter and Facebook should be fixed now.

**Comment by MasDevProject** [comment]
I cant confirm. Facebook and Twitter work fine.
Google still has the same problem.

**Comment by ntrogh** [comment]
For Google, there is indeed still a problem - I'm checking this with the Azure Mobile App SDK team.
Thanks for confirming Twitter and FB work ok.

**Comment by ntrogh** [comment]
Problem is linked to an [issue in Xamarin.Auth](https://github.com/xamarin/Xamarin.Auth/issues/137). For Android I have not yet found a workaround, but for iOS you can check [this](https://forums.xamarin.com/discussion/comment/247556/#Comment_247556).
