### ISSUE TITLE
The request could not be completed (internal server error)

### ISSUE THREAD

**Issue by Inviasubito** [msdxbelux/XamarinAlliance#7]
Hello,

I have been having a reoccurring problem when connecting to Azure services. The error which occurs is as follows:
"The request could not be completed (internal server error)". 

I even tried with other applications, but I recieve the same error which states "Internal Server Error". 

Would you'd be able to give me any advice as to what the issue may be and how I can resolve it?

Kind regards

Alessandro

**Comment by ntrogh** [comment]
Have you set up your own Azure Mobile App or are you using the shared Azure backends that we created for you? Can you provide some details about the implementation technology for the backend (C#, Node.js).

**Comment by Inviasubito** [comment]
The backend is in C#. I have also tried with your azure mobile app and with other apps

**Comment by ntrogh** [comment]
Can you provide more details about the error you're getting when connecting to the shared Azure backend? Could you provide some code to repro?

**Comment by Inviasubito** [comment]
Hello, with the last uodate of visual studio 2017, the error was fixed!

Thank you!
